title: Just Some Smart Guide
description: Track info for Mario Kart World
theme: just-the-docs

url: https://justsomesmartguide.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

  just_the_docs:
  search-override_css:
  - /assets/css/search-override.css
  
