title: Just Some Smart Guide
description: Track info for Mario Kart World
theme: just-the-docs

url: https://justsomesmartguide.github.io

color_scheme: custom

favicon_ico: "/assets/icons/app-icon-256.ico"
