title: Just Some Smart Guide
description: Track info for Mario Kart World
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://justsomesmartguide.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
